### ISSUE TITLE
У раунді 2 невірний порядок сортування

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/openprocurement.auction#31]
Учасник з наймешною ціновою пропозицією робить хід передостаннім

![image](https://cloud.githubusercontent.com/assets/9398532/12197459/d2b47682-b60f-11e5-8376-db32dd68bcd1.png)

**Comment by myroslav** [comment]
Потрібно перетестувати на sandbox, якщо все гаразд, то викладемо на production
