### ISSUE TITLE
Невірно обрахована початкова ставка учасника 2

### ISSUE THREAD

**Issue by andriykucherenko** [openprocurement/openprocurement.auction#32]
при тому, що цей учасник подавав ставку 100,000 (і не міг подати вище через те, що ця сумма є лімітом), у аукціоні вона відобразилась як 118 055, 56

![image](https://cloud.githubusercontent.com/assets/9398532/12197497/1fb9fd58-b610-11e5-9957-7319479aaa8f.png)

**Comment by ktarasz** [comment]
Змінено "Режим приведення ціни - до Моєї"

**Comment by andriykucherenko** [comment]
Так і що це означає? Я правильно розумію, що "До моєї" -- це "До фактичної ціни, поданої постачальником"? Якщо так, то баг залишається. у цьому аукціоні ніхто не подавав ціну 118К

**Comment by ktarasz** [comment]
Приведення до фактичної ціни, але коефіцієнтом залогованого учасника ... В цьому режимі для   ціна для залогованого учасника буде відповідати ( фактичній ціні ). Ціни інших учасників приводяться до фактичної з використанням коефіцієнту залогованого учасника (коефіцієнти інших учасників на  час проведення аукціону закриті). Ціни інших учасниців не є реальними і слугують лише для порівняння власної фактичної ставки з іншими

**Comment by andriykucherenko** [comment]
Соррі, це якось ви нагорнули поза межами розуміння середніх здібностей :(
